/**
 *
 * @author M Harist Naufal
 */
public class MyException extends Exception {
    private String Teks;

    public MyException(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws Exception {
        System.out.println("Tampil");
        if (s.equals("Dinar")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("Fadil");
            tampil("Dinar");
        } catch (MyException ex) {
            System.out.println("Tangkap: " + ex);
        }
    }
}